name: CI

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: purescript-contrib/setup-purescript@v2.0.0
      - run: |
          npx bower install
          npx pulp build
          npx pulp build --include test
